### ISSUE TITLE
error calling eq: invalid type for comparison

### ISSUE THREAD

**Issue by rguthriemsft** [kubernetes/helm#2979]
I was going through the getting started and in the section on flow control and if a value is commented out in my values.yaml (in this case the drink attribute), adding flow control eq operator throws an error like below when I run:

`helm install --debug --dry-run <My Chart>`

Output:
`Error: render error in "mychart/templates/configmap.yaml": template: mychart/templates/configmap.yaml:9:8: executing "mychart/templates/configmap.yaml" at <eq .Values.favorite....>: **error calling eq: invalid type for comparison**`

**configmap.yaml**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | default "tea" | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
  {{ if eq .Values.favorite.drink "coffee" }}mug: true{{ end }}
```

**values.yaml**

```
favorite:
  #drink: coffees
  food: pizza
```
                           
Is this a bug or am I missing something?

**HELM VERSION INFO:**
Client: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.1", GitCommit:"7cf31e8d9a026287041bae077b09165be247ae66", GitTreeState:"clean"}

**Comment by bacongobbler** [comment]
This is a side effect of Go's text/template package. If a value is unset, it is returned as a nil value. So really what you want to do in this case is

```
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | default "tea" | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
  {{ if .Values.favorite.drink and eq .Values.favorite.drink "coffee" }}mug: true{{ end }}
```

If values are considered "optional", the chart should check and determine if the value is unset first.

Hope this helps!

**Comment by bacongobbler** [comment]
Alternatively, if that value is required in order to render the chart, then you would want to use the [required function](https://docs.helm.sh/developing_charts/#know-your-template-functions).

**Comment by rguthriemsft** [comment]
I was able to get it working with your help with a slight modification:

  {{ if **( .Values.favorite.drink )** and eq .Values.favorite.drink "coffee" }}mug: true{{ end }}

How do I submit a documentation update as this was pulled from https://docs.helm.sh/chart_template_guide/#getting-started-with-a-chart-template in the section on if/else?

**Comment by bacongobbler** [comment]
Making a change to https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/getting_started.md in the form of a PR will update https://docs.helm.sh :)

**Comment by AnumSheraz** [comment]
You are comparing "string" with a variable .Values.favorite.drink of some unknown type. How about casting that variable to string ?

```{{if eq (.Values.favorite.drink | toString) "coffee"}}```

**Comment by bridgetkromhout** [comment]
Hi, @AnumSheraz - thanks for commenting. This issue is long-since resolved; if you'd like to participate in a more recent discussion it's in https://github.com/helm/helm/issues/6376, and if you'd like to submit a pull request to improve docs, the page you probably want is here: https://github.com/helm/helm-www/blob/master/content/en/docs/chart_template_guide/control_structures.md

**Comment by jdoylei** [comment]
Just leaving a comment here since between #6376 and this issue, this is the one that's more obviously related to the [Chart Template Guide](https://helm.sh/docs/chart_template_guide/control_structures/) / getting started example, and as of Helm 3.5.2 and today's guide, the guide has the same issue.  I ran through all the suggestions in #6376 and this issue to understand what works and what doesn't, a good learning experience for a Helm newbie like myself.  FWIW:

Variations that work in Helm 3.5.2 (personally I think the first variation is easiest to understand):

```
  {{if eq (.Values.favorite.drink | default "") "coffee"}}mug: "true"{{ end }}

  {{ if eq (default "" .Values.favorite.drink) "coffee" }}mug: "true"{{ end }}

  {{if eq (.Values.favorite.drink | toString) "coffee"}}mug: "true"{{ end }}

{{- if .Values.favorite.drink }}
{{- if eq .Values.favorite.drink "coffee" }}
  mug: "true"
{{- end }}
{{- end }}
```

Variations with `error calling eq: incompatible types for comparison` (the first variation is the one from the Chart Template Guide):

```
  {{ if eq .Values.favorite.drink "coffee" }}mug: "true"{{ end }}

  {{ if eq (default .Values.favorite.drink "") "coffee" }}mug: "true"{{ end }}

  {{- if and (.Values.favorite.drink) (eq .Values.favorite.drink "coffee") }}mug: "true"{{ end }}
```

Variation with `drink is not a method but has arguments`:

```
  {{ if .Values.favorite.drink and eq .Values.favorite.drink "coffee" }}mug: "true"{{ end }}
```

Variation with `can't give argument to non-function .Values.favorite.drink`:

```
  {{ if ( .Values.favorite.drink ) and eq .Values.favorite.drink "coffee" }}mug: "true"{{ end }}
```
